name       : kalarmcal
version    : 20.08.1
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kalarmcal-20.08.1.tar.xz : 745515662c23154480e73f4a8d6e9ec760d01770383c1dd7f31d3f1463be7602
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcompletion-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
