name       : kalarmcal
version    : 20.08.3
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kalarmcal-20.08.3.tar.xz : c65c3746b13c44ae6a05bfbb213882b9d3ebf608748e20696df50a49fc8830c5
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcompletion-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
