name       : kalarmcal
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kalarmcal-17.12.2.tar.xz : c21c197a2ddaf246cc1cfe35458b5ba731a55ec2bd61488be2f21c2203305a12
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data.
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kholidays-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
