name       : kalarmcal
version    : 18.04.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kalarmcal-18.04.3.tar.xz : 74a2d5e979b6d5d7e5b5a36899cf0efe2956582ab458e29f2bee8fd9185b9fae
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kholidays-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
