name       : kalarmcal
version    : 20.08.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kalarmcal-20.08.0.tar.xz : bd4f048a976829ee5768b9d26aebe4efbbfa0a2991486c8f57f250fe4198532c
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcompletion-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
