name       : kalarmcal
version    : 21.04.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kalarmcal-21.04.2.tar.xz : 95ff7c2b4dce435b5a214f1f126faaf1c6bb064624f8ad7596b1981e5a390dfe
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - akonadi-devel
    - kcalutils-devel
    - kcalendarcore-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
rundeps    :
    - devel :
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
