name       : kalarmcal
version    : 18.12.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kalarmcal-18.12.2.tar.xz : f2fb28dcd9bfd0c5c3d7fde76279999f4f5863d3f21bd9a3f47f77ee0b9f110d
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
