name       : kalarmcal
version    : 18.04.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kalarmcal-18.04.0.tar.xz : c7bdb479471ad0a4a8e5336ee9283bdb910479e96b12ecfb21c4f99ebfe4fb5a
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Provides access to and handling of KAlarm calendar data.
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kholidays-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
