name       : kalarmcal
version    : 21.08.1
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kalarmcal-21.08.1.tar.xz : ca9d7dd035064141b9ee7448947b50b9699a7b8f6c236f1ab93293e201cc1ee8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - akonadi-devel
    - kcalutils-devel
    - kcalendarcore-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
rundeps    :
    - devel :
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
