name       : kalarmcal
version    : 17.12.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kalarmcal-17.12.1.tar.xz : e5e111a571d19eac6c6ea6bb79a7abe8cd9f025823e4412680c55bb672c1d617
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data.
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kholidays-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
