name       : kalarmcal
version    : 19.04.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/kalarmcal-19.04.0.tar.xz : ec0790d2b04bcd3a37a221bdbf4a10f94ff7dd8ac0228e773ce9fac14bbebf6e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
