name       : kalarmcal
version    : 18.12.1
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kalarmcal-18.12.1.tar.xz : c73abb362a98c07c22bddf5a9bca88f49a1d99226eae544fbfd5534ac45bd373
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
