name       : kalarmcal
version    : 18.04.2
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kalarmcal-18.04.2.tar.xz : 268bb1e48232de79c0b9d84f61e089f0f8eb61838ec2307a69d422977d99494f
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kholidays-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
