name       : kalarmcal
version    : 19.08.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/kalarmcal-19.08.0.tar.xz : 5f764d58716e7d271fac4cb3a4df6ab157014533782c47c38bacab59ca669419
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kholidays-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
