name       : kalarmcal
version    : 21.08.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kalarmcal-21.08.0.tar.xz : 0734864f64f18bf8bdce720c323b65e206170758f2385aa4b4f2a021f4c38aec
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - akonadi-devel
    - kcalutils-devel
    - kcalendarcore-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
rundeps    :
    - devel :
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
