name       : kalarmcal
version    : 21.12.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kalarmcal-21.12.0.tar.xz : 1dc2619888c33757a39d9ba2bd204159e47aae01cde963c7e9439d6c1b3a6066
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - akonadi-devel
    - kcalutils-devel
    - kcalendarcore-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - kpimtextedit-devel
    - kxmlgui-devel
    - libboost-devel
rundeps    :
    - devel :
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
