name       : kalarmcal
version    : 17.04.1
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kalarmcal-17.04.1.tar.xz : f98df0545845fb166260ae53aaa73723c32e2c4b91fc0c7265f0d4addcd3412e
license    : LGPL-2.1
component  : desktop.library
summary    : Provides access to and handling of KAlarm calendar data.
description: |
    This library provides access to KAlarm calendar data, but not to the storage of the data, which is handled by Akonadi (or by build option, KResources).
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - akonadi-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kdelibs4support-devel
    - kidentitymanagement-devel
    - kholidays-devel
    - kpimtextedit-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
